package com.iptv.hn.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.iptv.hn.entity.AdsDataBean;

import com.iptv.hn.dao.AdsDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adsDataBeanDaoConfig;

    private final AdsDataBeanDao adsDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adsDataBeanDaoConfig = daoConfigMap.get(AdsDataBeanDao.class).clone();
        adsDataBeanDaoConfig.initIdentityScope(type);

        adsDataBeanDao = new AdsDataBeanDao(adsDataBeanDaoConfig, this);

        registerDao(AdsDataBean.class, adsDataBeanDao);
    }
    
    public void clear() {
        adsDataBeanDaoConfig.clearIdentityScope();
    }

    public AdsDataBeanDao getAdsDataBeanDao() {
        return adsDataBeanDao;
    }

}
